# Generated by Django 5.0 on 2023-12-27 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('followk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followk', to=settings.AUTH_USER_MODEL)),
                ('followsh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followsh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
